import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Text Editor App</title>
        <meta name="description" content="Generated by create next app, made by Jairo Rubio" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <section>
        
      </section>
    </div>
  )
}
